package duh_test

import (
	"os"
	"path/filepath"
	"testing"

	duh "github.com/duh-rpc/duh-cli"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateDuhCreatesIteratorWithListOps(t *testing.T) {
	specPath, stdout := setupTest(t, specWithListOp)
	tempDir := filepath.Dir(specPath)

	exitCode := duh.RunCmd(stdout, []string{"generate", specPath})

	require.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "✓")

	clientContent, err := os.ReadFile(filepath.Join(tempDir, "client.go"))
	require.NoError(t, err)
	content := string(clientContent)

	assert.Contains(t, content, "duh.NewIterator")
	assert.Contains(t, content, "*duh.Iterator")
	assert.NotContains(t, content, "iterator.go")

	_, err = os.Stat(filepath.Join(tempDir, "iterator.go"))
	require.Error(t, err)
	assert.True(t, os.IsNotExist(err))
}

func TestGenerateDuhSkipsIteratorWithoutListOps(t *testing.T) {
	specPath, stdout := setupTest(t, simpleValidSpec)
	tempDir := filepath.Dir(specPath)

	exitCode := duh.RunCmd(stdout, []string{"generate", specPath})

	require.Equal(t, 0, exitCode)
	assert.Contains(t, stdout.String(), "✓")
	assert.NotContains(t, stdout.String(), "iterator.go")

	_, err := os.Stat(filepath.Join(tempDir, "iterator.go"))
	require.Error(t, err)
	require.True(t, os.IsNotExist(err))
}

func TestIteratorStructure(t *testing.T) {
	specPath, stdout := setupTest(t, specWithListOp)
	tempDir := filepath.Dir(specPath)

	exitCode := duh.RunCmd(stdout, []string{"generate", specPath})

	require.Equal(t, 0, exitCode)

	clientContent, err := os.ReadFile(filepath.Join(tempDir, "client.go"))
	require.NoError(t, err)
	content := string(clientContent)

	assert.Contains(t, content, "duh.NewIterator")
	assert.Contains(t, content, "*duh.Iterator")
	assert.Contains(t, content, "UsersListIter")
	assert.NotContains(t, content, "PageFetcher")
	assert.NotContains(t, content, "GenericIterator")
	assert.NotContains(t, content, "FetchPage")

	assert.NotContains(t, content, "//go:build")
	assert.Contains(t, content, "Code generated by 'duh generate'")
	assert.Contains(t, content, "DO NOT EDIT")
	assert.Contains(t, content, "package api")
}
